#!/usr/bin/env python3
import sys
from src.solver.solver import solve_instance, check_solution_tree

def main():
    if len(sys.argv) != 2:
        print("Usage: ./sc_solver path_to_input_instance", file=sys.stderr)
        sys.exit(1)

    instance_path = sys.argv[1]
    solve_instance(instance_path)
    # after solving, validate generated .sol files
    check_solution_tree()

if __name__ == "__main__":
    main()